# Generated by Django 5.1 on 2024-08-12 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_depositandwithdraw_transfer_delete_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositandwithdraw",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
